apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: cake-delight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: cakedelight/api-gateway:1.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8091
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8091
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
