apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: cake-delight
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: NodePort
